token-url: "/golemio-api.cert"
logs-url: "/data/logs/"
data:
  stage:
    path: "/data/data/stage/"
  gtfs:
    path: "/data/data/stops/"
    no-delete-list: ["stops.txt"]
    #no-delete-list: ['agency.txt','calendar.txt','calendar_dates.txt','fare_attributes.txt','fare_rules.txt','feed_info.txt','levels.txt','pathways.txt','routes.txt','route_stops.txt','route_sub_agencies.txt','stops.txt','transfers.txt','trips.txt']
  rtvp:
    path: "data/data/delay/"
    json-separator: "__"
    filters:
      properties__trip__gtfs__route_id: "L3"
      #properties__trip__vehicle_type__description_cs: "autobus"
pid:
  gtfs:
    url: "http://data.pid.cz/PID_GTFS.zip"
  rtvp:
    url: 'https://api.golemio.cz/v2/vehiclepositions'
log-setting:
    orig-path: "/data/logs/"
log:
  version: 1
  formatters:
    standard:
      format: '%(asctime)s - %(levelname)s - %(name)s - %(filename)s.%(funcName)s()(%(lineno)d): %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      level: INFO
      formatter: standard
      stream: ext://sys.stdout
    #file:
      #class: logging.FileHandler
      #level: DEBUG
      #formatter: standard
      #filename: "/data/logs/"
    rotate:
      class: logging.handlers.TimedRotatingFileHandler
      level: INFO
      formatter: standard
      filename: "/data/logs/wf_load_data.log"
      when: 'midnight'
  root:
    level: DEBUG
    handlers: [console,rotate]
    propogate: yes